// Code generated by "stringer -type=RabEnv -optionType=RabOption"; DO NOT EDIT.
package example

import (
	"github.com/caarlos0/env/v6"
)

type RabOption func(*RabEnv)

func FromRabEnv(v *RabEnv) RabOption {
	return func(c *RabEnv) { *c = *v }
}
func RabOptionParseEnv(eo env.Options) (opts []RabOption, err error) {
	var o RabEnv
	opts = append(opts, FromRabEnv(&o))
	return opts, env.Parse(&o, eo)
}
func ApplyRabOptions(opts ...RabOption) (res RabEnv) {
	env.Parse(&res, env.Options{Environment: make(map[string]string)})
	for _, o := range opts {
		o(&res)
	}
	return
}
func WithHomeRabOption(v string) RabOption { return func(o *RabEnv) { o.Home = v } }
