// Code generated by "envopts -type=RabEnv -optionType=RabOption"; DO NOT EDIT.
package example

import (
	"github.com/caarlos0/env/v6"
)

// RabOption is a functional option to configure RabEnv
type RabOption func(*RabEnv)

// FromRabEnv takes fully configured RabEnv and returns it as an option. Can be used to parse environment
// variables manually and provide the result in places where an option argument is expected.
func FromRabEnv(v *RabEnv) RabOption {
	return func(c *RabEnv) { *c = *v }
}

// RabOptionParseEnv will parse environment variables into a slice of options. Any options for parsing the
// environment can be supplied, for example to parse under a prefix.
func RabOptionParseEnv(eo env.Options) (opts []RabOption, err error) {
	var o RabEnv
	opts = append(opts, FromRabEnv(&o))
	return opts, env.Parse(&o, eo)
}

// ApplyRabOptions will merge all options into the resulting RabEnv while also ensuring default values are
// always set.
func ApplyRabOptions(opts ...RabOption) (res RabEnv) {
	env.Parse(&res, env.Options{Environment: make(map[string]string)})
	for _, o := range opts {
		o(&res)
	}
	return
}

// WithHomeRabOption configures: User's home directory
func WithHomeRabOption(v string) RabOption { return func(o *RabEnv) { o.Home = v } }
